version: '2'
services:
    projetarchi-mongodb:
        container_name: projetarchi-mongodb
        image: mongo:3.2.10
        ports:
            - "27017:27017"
        # volumes:
        #     - ~/volumes/jhipster/projetArchi/mongodb/:/data/db/
